# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 654217d781147dedbc74bfe883523e1646b2d16e2f0255ed316ccdfa6db46d2396ab23e513f3f7938b7aff42fc5a96efee728de4915cb9a61b5ca5d8f930fd65
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  github_username: <%= ENV["GITHUB_USERNAME"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>
  github_token: <%= ENV["GITHUB_TOKEN"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  rorl_twitter_key: <%= ENV["RORL_TWITTER_KEY"] %>
  rorl_twitter_secret: <%= ENV["RORL_TWITTER_SECRET"] %>

test:
  secret_key_base: 49ecef9158ca5385c17d21e716b7196be7c72e182c60f1ac8a1b7924012889760dac125ae6eea2e712395423e9ec7eef898a0402a750909db5fcc2d5cc55c344
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  github_username: <%= ENV["GITHUB_USERNAME"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>
  github_token: <%= ENV["GITHUB_TOKEN"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  rorl_twitter_key: <%= ENV["RORL_TWITTER_KEY"] %>
  rorl_twitter_secret: <%= ENV["RORL_TWITTER_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SB_SECRET_KEY_BASE"] %>
  omniauth_provider_key: <%= ENV["SB_OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["SB_OMNIAUTH_PROVIDER_SECRET"] %>
  github_username: <%= ENV["SB_GITHUB_USERNAME"] %>
  github_password: <%= ENV["SB_GITHUB_PASSWORD"] %>
  github_token: <%= ENV["SB_GITHUB_TOKEN"] %>
  twitter_consumer_key: <%= ENV["SB_TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["SB_TWITTER_CONSUMER_SECRET"] %>
  rorl_twitter_key: <%= ENV["SB_RORL_TWITTER_KEY"] %>
  rorl_twitter_secret: <%= ENV["SB_RORL_TWITTER_SECRET"] %>
